name: Download Convox CLI
description: Download the Convox CLI and place it in $PATH
author: https://github.com/liamdawson
requirements:
  - curl
configuration:
  additionalProperties: false
  properties:
    os:
      type: string
      default: linux
      enum:
        - linux
        - macos
    generation:
      default: 3
      oneOf:
        - type: [number, string]
          enum:
            - 2
            - "2"
            - 3
            - "3"
        - type: object
          additionalProperties: false
          properties:
            3:
              type: object
              additionalProperties: false
              required:
                - version
              properties:
                version:
                  type: string
                  default: "latest"
