#!/bin/bash
set -euo pipefail

target_os="${BUILDKITE_PLUGIN_DOWNLOAD_CONVOX_CLI_OS:-linux}"

if [ "${BUILDKITE_PLUGIN_DOWNLOAD_CONVOX_CLI_GENERATION_3_VERSION:-}" != "" ]; then
  cli_url="https://github.com/convox/convox/releases/download/${BUILDKITE_PLUGIN_DOWNLOAD_CONVOX_CLI_GENERATION_3_VERSION}/convox-${target_os}"
else
  case "${BUILDKITE_PLUGIN_DOWNLOAD_CONVOX_CLI_GENERATION:-3}" in
    2)
      cli_url="https://convox.com/cli/${target_os}/convox";;
    3)
      cli_url="https://github.com/convox/convox/releases/latest/download/convox-${target_os}";;
  esac
fi

HOOKS_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
PLUGIN_DIR="$(cd "${HOOKS_DIR}/.." && pwd)"
BIN_DIR="${PLUGIN_DIR}/bin"

mkdir -p "$BIN_DIR"

! [ -f "${BIN_DIR}/convox" ] || rm "${BIN_DIR}/convox"

curl -L "$cli_url" -o "${BIN_DIR}/convox"
chmod +x "${BIN_DIR}/convox"

export PATH="${BIN_DIR}:${PATH}"

echo "Downloaded Convox CLI version $(convox --version)"
